schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
  pipelines:
  - pipeline: oci-labs.rosidl_typesupport_opendds
    source: oci-labs.rosidl_typesupport_opendds
    trigger: 
      branches:
      - master

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-18.04'
  container: objectcomputing/opendds_ros2:latest
  steps:
  - script: |
      printenv
      pwd
      ls
      echo "agend build directory"
      echo $(Agent.BuildDirectory)
    displayName: filesystem check
  - script: |
      cd $(Agent.BuildDirectory)/s
      git clone https://github.com/oci-labs/rosidl_typesupport_opendds.git
    displayName: clone rosidl_typesupport_opendds
  - script: |
        cd $(Agent.BuildDirectory)
        git clone https://github.com/adamsj-oci/rmw_build
        vcs import s < rmw_build/ros2.repos
        echo "ls"
        ls
        echo "ls s"
        ls s/
    displayName:  rmw build repo and dependencies
  - script: |
        cd $(Agent.BuildDirectory)
        source /opt/OpenDDS/setenv.sh
        source /opt/ros/eloquent/setup.bash
        printenv|grep DDS
        printenv|grep ROS
        colcon build --symlink-install --packages-up-to rmw_opendds_cpp
    displayName:  build up to rmw_opendds_cpp
  - script: |
        cd $(Agent.BuildDirectory)
        source /opt/OpenDDS/setenv.sh
        source /opt/ros/eloquent/setup.bash
        source $(Agent.BuildDirectory)/install/local_setup.bash
        printenv|grep DDS
        printenv|grep ROS
        colcon build --symlink-install --packages-up-to rcl_interfaces examples_rclcpp_minimal_publisher examples_rclcpp_minimal_subscriber
    displayName:  build simple tests
  - script: |
        cd $(Agent.BuildDirectory)
        source /opt/OpenDDS/setenv.sh
        source /opt/ros/eloquent/setup.bash
        source $(Agent.BuildDirectory)/install/local_setup.bash
        printenv|grep DDS
        printenv|grep ROS
        export RMW_IMPLEMENTATION=rmw_opendds_cpp
        env|grep RMW
        ros2 run examples_rclcpp_minimal_subscriber subscriber_member_function_twenty& 
        ros2 run examples_rclcpp_minimal_publisher publisher_member_function_twenty
    displayName:  run simple tests