schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
  pipelines:
  - pipeline: oci-labs.rosidl_typesupport_opendds
    source: oci-labs.rosidl_typesupport_opendds
    trigger:
      branches:
      - master

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-18.04'
  container: objectcomputing/opendds_ros2:latest
  steps:
  - script: |
      printenv
      pwd
      ls
      echo "agend build directory"
      echo $(Agent.BuildDirectory)
    displayName: filesystem check
  - script: |
      cd $(Agent.BuildDirectory)/s
      git clone https://github.com/oci-labs/rosidl_typesupport_opendds.git
      pwd
      cd $(Agent.BuildDirectory)/rosidl_typesupport_opendds
      pwd
      git checkout 7eb0964b11548566b95dae85719d835a33a0faf1
    displayName: clone rosidl_typesupport_opendds
  - script: |
        cd $(Agent.BuildDirectory)
        git clone https://github.com/adamsj-oci/rmw_build
        vcs import s < rmw_build/ros2.repos
        echo "ls"
        ls
        echo "ls s"
        ls s/
    displayName:  rmw build repo and dependencies
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/build_all.sh
    displayName:  build rmw and tests (build_all.sh)
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/run_ci_test.sh
    displayName:  run tests (run_ci_test.sh)
