schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
  pipelines:
  - pipeline: oci-labs.rosidl_typesupport_opendds
    source: oci-labs.rosidl_typesupport_opendds
    trigger:
      branches:
      - master

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-20.04'
  container: objectcomputing/opendds_ros2_foxy:latest
  steps:
  - script: |
      printenv
      pwd
      ls
      echo "Agent.BuildDirectory"
      echo $(Agent.BuildDirectory)
    displayName: filesystem check
  - script: |
      cd $(Agent.BuildDirectory)/s
      git clone -b foxy https://github.com/oci-labs/rosidl_typesupport_opendds
    displayName: clone rosidl_typesupport_opendds
  - script: |
        cd $(Agent.BuildDirectory)
        git clone -b foxy-release https://github.com/adamsj-oci/rmw_build
        vcs import s < rmw_build/ros2.repos
        echo "ls"
        ls
        echo "ls s"
        ls s/
    displayName:  rmw build repo and dependencies
  - script: |
        cd $(Agent.BuildDirectory)
        echo "SUMMARY"
        ./rmw_build/all_git_repos.sh -S
        echo "CURRENT BRANCHES"
        ./rmw_build/all_git_repos.sh -B
    displayName:  all repo summary
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/build_all.sh
    displayName:  build rmw and tests (build_all.sh)
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/run_ci_test.sh
    displayName:  run tests (run_ci_test.sh)
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/run_ci_test_rpc.sh
    displayName:  run tests (run_ci_test_rpc.sh)
  - script: |
        rm -rf build
        rm -rf install
    displayName:  remove previous build artifacts (only do this short term)
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/build_system_test.sh
    displayName:  build system tests
  - script: |
        cd $(Agent.BuildDirectory)
        ./rmw_build/run_system_test.sh
    displayName:  run system tests
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/*.xml'
      searchFolder: '$(Agent.BuildDirectory)/build/test_communication/'
