schedules:
- cron: "0 7 * * SUN"
  displayName: Weekly Sunday
  branches:
    include:
    - master
  always: true

resources:
  pipelines:
  - pipeline: oci-labs.rosidl_typesupport_opendds
    source: oci-labs.rosidl_typesupport_opendds
    trigger: 
      branches:
      - master

jobs:
- job: Linux
  timeoutInMinutes: 90
  pool:
    vmImage: 'ubuntu-18.04'
  container: objectcomputing/opendds_ros2:latest
  steps:
  - script: |
      printenv
      echo hello
      pwd
      ls
    displayName: filesystem check
  - script: |
      git clone https://github.com/oci-labs/rosidl_typesupport_opendds.git
    displayName: clone rosidl_typesupport_opendds
  - script: |
        source /opt/OpenDDS/setenv.sh
        source /opt/ros/eloquent/setup.bash
        printenv|grep DDS
        printenv|grep ROS
        colcon build --symlink-install --packages-up-to rmw_opendds_cpp
        echo "done"
        ls
        ls ..
    displayName: build rmw
