#include <dds/DdsDcpsCore.idl>

const long KEY_HASH_LENGTH_16 = 16;
typedef octet OctetArray16[KEY_HASH_LENGTH_16]; 

@topic struct OpenDDSStaticSerializedData {
  @key OctetArray16       key_hash;
  DDS::OctetSeq  serialized_key;
  DDS::OctetSeq  serialized_data;
};
